Add `libc++-dev` package to linux environment
rust-lang/crates-build-env pull request #121
Opened 2023-01-26 09:25 UTC by nicoburns

We're using `libc++` (clang's C++ standard library) instead of `libstdc++` for [yoga-rs](https://github.com/bschwind/yoga-rs) because using `libstdc++` / using whatever is set as default was causing bindgen to generate code that wouldn't compile.

However, this dependency is missing in the build environment which is causing building docs for `docs.rs` to fail (https://github.com/rust-lang/docs.rs/issues/2017)

2023-01-26 09:32 UTC, nicoburns commented
https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-14/+bug/1989124

2023-02-04 07:18 UTC, syphar approved these changes

2023-02-04 07:19 UTC, syphar requested changes
I was too quick, 

I see the build is failing, this would need to be fixed before merging.

2026-07-03 14:49 UTC, syphar commented
Closing for inactivity, feel free to reopen / create a new PR if the need arises.

2026-07-03 14:49 UTC, closed without merging