Update to Noble 24.04
rust-lang/crates-build-env pull request #151
Opened 2024-08-21 10:18 UTC by Mottl

This commit updates docker images to **Ubuntu 24.04**

The following packages were removed by Ubuntu since 22.04:
```
libatk1.0-data
libdns-export1110
libgcc1
libgl1-mesa-glx
libgles2-mesa
libhdf5-openmpi-103
libicu-le-hb-dev
libicu-le-hb0
libilmbase25
libirs161
libisc-export1105
libisc1105
libisccc161
libisccfg163
liblwres161
libmpdec3
libprocps8
libtinfo-dev
libwayland-egl1-mesa
libwebkit2gtk-4.0-dev
```

2024-08-22 05:16 UTC, syphar commented
@Mottl  thank you for the work! 

I'll not be able to thoroughly review this week, but you could already help by checking this: 

were any of the removed packages added via PR later? Or were they here on the package list from the start?

2024-09-02 17:52 UTC, syphar commented
there was a new PR with new packages, can you add these / rebase this PR? https://github.com/rust-lang/crates-build-env/pull/153 

Were you able to answer this question? 

> were any of the removed packages added via PR later? Or were they here on the package list from the start?

a `git blame` will probably give you that info. 

I can probably onyl check it later this week

2024-09-02 17:53 UTC, syphar reviewed
.

2024-09-02 18:00 UTC, syphar requested changes
thank you for working on this, 

to summarize what we need to do to bring this forward: 
- compile a list of removed packages (some where missing), and check if they were specifically added for a crate, or in there from the beginning 
- then I'll run builds for some crates with the resulting image 

then we can try merging

2025-03-19 06:14 UTC, Mottl commented
Closed due to  #168

2025-03-19 06:14 UTC, closed without merging